import '/imports/api/products/products.js';
import '/imports/api/products/server/publication/list_product.js';
import '/imports/api/products/server/publication/one_product.js';
import '/imports/api/products/server/methods/add_review.js';
import '/imports/api/products/server/methods/update_product.js';
import '/imports/api/products/server/methods/insert_product.js';
import '/imports/api/reviews/reviews.js';
import '/imports/api/reviews/server/methods/insert_review.js';
import '/imports/api/reviews/server/publications/product_reviews.js';
